name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3

    - name: Build RELEASE
      run: make build-release
      
    - name: Build DEBUG
      run: make build-release
